LINKED LIST/c or cpp/Intersection.c
LINKED LIST/c or cpp/Merge_Sort.c
LINKED LIST/c or cpp/Remove_Duplicates.c
LINKED LIST/c or cpp/Unions.c
LINKED LIST/c or cpp/dll.h

This is a C code that implements the mathematical concept of sets using doubly linked list.

C code to implement sets

---

SORTING/c or cpp/Different_Sorts.c

C code for Bubble sort, Insertion sort & Selection sort

Bubble sort, Insertion sort & Selection sort

---

STACK AND QUEUES/c or cpp/COE19B046_Infix.c
STACK AND QUEUES/c or cpp/Stack.h

This is a C code to convert an infix expression to postfix

Code to convert Infix to Postfix

---

LINKED LIST/c or cpp/Sparse_Matrix_creation.c

This is a C code for Sparse matrix creation using singly linked list

C code for Sparse matrix creation

---

STACK AND QUEUES/c or cpp/COE19B046_list.h
STACK AND QUEUES/c or cpp/Queue_ADT.c
STACK AND QUEUES/c or cpp/Stack_ADT.c

Added C code for Queue, and Stack. COE19B046_list.h consists of all the functions used by the stack and queue codes

C code for stacks and queues

---

LINKED LIST/c or cpp/CircularLinkedList.cpp

Insertion at various locations in circular linked list

Circular linked list program

---

RECURSION/c or cpp/Contributors.md
RECURSION/c or cpp/Factorial.cpp

Added Factorial code using recursion in cpp

Added Factorial.cpp in RECURSION/c or cpp folder

---

STACK AND QUEUES/c or cpp/Stack_Operations.cpp

Menu driven program in CPP using Stack data structure By Almas Dinani

Stack Operations in C++

---

DYNAMIC PROGRAMMING/c or cpp/Contributors.md
DYNAMIC PROGRAMMING/c or cpp/minimum_cost.cpp

I have added minimum cost program

Adding minimum cost

---

.idea/Simple_calculator.py

Simple Calculator made using Tkinter In Python

Simple Calculator program

---

SEARCHING/py/Contributors.md
SEARCHING/py/jumpsearch.py

Added JumpSearch in SEARCHING/py folder.

Added jumpsearch.py

---

LINKED LIST/py/Contributors.md
LINKED LIST/py/is_palindrome.py

palindrome check algorithm added

palindrome check algo added

---

OBJECT ORIENTED PROGRAMMING/c or cpp/Contributors.md
OBJECT ORIENTED PROGRAMMING/c or cpp/friendfunction.cpp
SORTING/c or cpp/Contributors.md
SORTING/c or cpp/bubblesort.cpp

Added friend function program example for cpp in oop section.
Also added my name in contributors.
please merge if find useful and tag accordingly.

Added friend function program

---

SORTING/c or cpp/Contributors.md
SORTING/c or cpp/bubblesort.cpp

added bubble sort program with an example of generic programming with both ascending and descending order. 
Added my name to the contributors file too.
if you find this useful merge and label accordingly.

added bubble sort program

---

HEAP/py/Contributors.md
HEAP/py/heap.py

Adding Heap

---

STRINGS/c or cpp/encodestring.cpp

This is my first contribution for HacktoberFest 2020.
This code takes input from the user and converts it into a encoded string.

Added encodestring.cpp

---

TREES/c or cpp/BinarySearchTree.cpp
TREES/c or cpp/Contributors.md

added binary search program in cpp and also added name in contributors list

Added binary search tree program in cpp

---

STRINGS/py/domain.py

This code prompts user to enter their email id and extracts domain name from the email id .

Added domain.py

---

SORTING/py/MergeSort.py

Add Merge Sort Algorithm using Python language

Add Merge Sort in Python

---

SORTING/py/Contributors.md
SORTING/py/SelectionSort.py

Add python selection sort and update contributor.md file

Add python selection sort and update contributor file

---

SORTING/py/BillCalculation.py

A class to keep product record and generate the bill displaying the total amount.

Sorting a Bill with pricing in Python

---

DYNAMIC PROGRAMMING/c or cpp/BinomialCoefficient.cpp
DYNAMIC PROGRAMMING/c or cpp/Contributors.md

A 1D Dynamic Programming solution to calculating Binomial Coefficient nCr

Added Binomial Coefficient via DP

---

EXPONENTIAITION BY SQUARING/py/Contributors.md
EXPONENTIAITION BY SQUARING/py/ModularExponentiation.py

An iterative approach to solving modular exponentiation in Python

Modular Exponentiation in Python

---

RECURSION/c or cpp/sum_of_square_of_binomial_coeffiecient/readme.md
RECURSION/c or cpp/sum_of_square_of_binomial_coeffiecient/sum_of_square_of_binomial_coefficient.cpp

Added the effiecient and Simplest Algorithm for Sum_Of_Sqaure_of_Binomail_coefficient.

Added_sum_of_square_of_binomial_coeffiecient

---

RECURSION/c or cpp/Contributors.md
RECURSION/c or cpp/Multiplication.c

added Multiplication using recursion

Multiplication using recursion

---

SORTING/py/Contributors.md
SORTING/py/HeapSort.py

Hi,
I have added a heap-sort code in python. Please do merge.
Thank you.

I have added heap sort code in python.

---

SEARCHING/c or cpp/Contributors.md
SEARCHING/c or cpp/binarySearch.cpp

Added the code for Binary search in CPP.

Added Binary search

---

LINKED LIST/c or cpp/Contributors.md
LINKED LIST/c or cpp/Doubly_Circular_Linked_List.c

Added Myself In The Contributors.md

Added Doubly Circular Linked List

---

DYNAMIC PROGRAMMING/c or cpp/Edit Distance.cpp
SORTING/py/3-way quick sort .py

Edit Distance(Without Backtracking)

Edit Distance in C++

---

SEARCHING/java/linear_search.java

Linear Search

---

HEAP/c or cpp/heap.cpp

C++ program for implementation of Heap Sort

Added the heap sort

---

HEAP/c or cpp/heap.cpp

C++ program for implementation 
of Iterative Heap Sort

Iterative Heap Sort

---

HEAP/c or cpp/k-aryheap.cpp

C++ program to demonstrate all operations of
k-ary Heap

k-ary Heap

---

TREES/c or cpp/postorder.cpp

Postorder tree traversal using both recursive and non-recursive ways.

postorder.cpp file added

---

TREES/c or cpp/ThreadedBinaryTree.cpp

ThreadedBinaryTree.cpp file added

---

LINKED LIST/c or cpp/Skiplist.cpp

A skip list to store a sorted list of elements or data with a linked list.

skiplist.cpp added

---

LINKED LIST/c or cpp/sorting linked list.c

Added a c code to check whether Linked List is sorted or not. Please review and merge it.

 Sorting Linked List
